name: Test 1
run-name: ${{ github.actor }} has triggered test action 🚀
on: [push]

jobs:
  detect-api-changes:
    name: Detect API Changes
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
    
        - name: Delete note.txt and main.note.txt if exist
          run: rm -f note.txt main.note.txt
    
        - name: Switch to main branch
          run: git checkout main
    
        - name: Create main.note.txt with text 'MAIN TEST'
          run: echo 'MAIN TEST' > main.note.txt
    
        - name: Switch back to dev branch
          run: git checkout dev
    
        - name: Create note.txt with text 'TEST'
          run: echo 'TEST' > note.txt
    
        - name: Checkout main.note.txt from main branch
          run: git checkout origin/main -- main.note.txt
    
        - name: Compare note.txt and main.note.txt
          run: |
            if cmp -s "note.txt" "main.note.txt"; then
              echo "The files are identical"
            else
              echo "The files are different"
            fi
    
        - name: Clean up
          run: rm -f note.txt main.note.txt
